In [1]:
#iMPORTING the libraries needed
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.svm import LinearSVR, SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor

import warnings
warnings.filterwarnings(action='ignore')

In [15]:
#loading the dataset
df = pd.read_excel('Burnout Rate - Before modelling.xlsx')
df.head()

,Unnamed: 0,Unnamed: 0.1,Employee ID,Project ID,Duration,Workload,Performance,Missed deadlines,Partly – Job satisfaction,Number of unplanned meetings,...,Video of the meeting:,Communication,OfficeLaptop,Periodic employee survey feedbacks,External factors,Personality style,Mood,Personality_style_Cat,burnout,Employee_burnout
0,0,1,fffe320039000123490320,4,8.0,2.0,3.8,13,Disagree,8,...,NaN,NaN,15.969746,NaN,NaN,INFJ,Positive,5,34.769746,Total burnout
1,1,2,fffe32003000360033003200,13,6.0,1.0,5.0,13,Strong Agree,10,...,NaN,NaN,8.109929,NaN,NaN,ENTP,Positive,3,23.109929,Moderate burnout
2,2,3,fffe3700360033003500,13,6.0,2.0,5.8,11,Disagree,9,...,NaN,NaN,12.304135,NaN,NaN,INTP,Positive,8,34.104135,Total burnout
3,3,4,fffe31003300320037003900,14,7.0,1.0,2.6,11,Disagree,12,...,NaN,NaN,12.970959,NaN,NaN,INTJ,Positive,7,30.570959,Alarming burnout
4,4,5,fffe32003400380032003900,2,7.0,3.0,6.9,12,Neither,13,...,NaN,NaN,9.206541,NaN,NaN,ENTJ,Positive,2,28.106541,Alarming burnout

In [16]:
df.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'Employee ID', 'Project ID', 'Duration',
       'Workload', 'Performance', 'Missed deadlines',
       'Partly – Job satisfaction', 'Number of unplanned meetings',
       'Number of meetings organized', 'Number of meetings participated',
       'Average meeting time per day/week',
       'Time series view of the usage of teams for the purpose of communication or documents',
       'General leave patterns', 'Sick leave(s)', 'Audio conversation',
       'Video of the meeting:', 'Communication', 'OfficeLaptop',
       'Periodic employee survey feedbacks', 'External factors',
       'Personality style', 'Mood', 'Personality_style_Cat', 'burnout',
       'Employee_burnout'],
      dtype='object')

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 27 columns):
 #   Column                                                                                Non-Null Count  Dtype
---  ------                                                                                --------------  -----
 0   Unnamed: 0                                                                            200 non-null    int64
 1   Unnamed: 0.1                                                                          200 non-null    int64
 2   Employee ID                                                                           200 non-null    object
 3   Project ID                                                                            200 non-null    int64
 4   Duration                                                                              200 non-null    float64
 5   Workload                                                                              199 non-null    float64
 6   Performance                                                                           200 non-null    float64
 7   Missed deadlines                                                                      200 non-null    int64
 8   Partly – Job satisfaction                                                             200 non-null    object
 9   Number of unplanned meetings                                                          200 non-null    int64
 10  Number of meetings organized                                                          200 non-null    int64
 11  Number of meetings participated                                                       200 non-null    float64
 12  Average meeting time per day/week                                                     200 non-null    float64
 13  Time series view of the usage of teams for the purpose of communication or documents  0 non-null      float64
 14  General leave patterns                                                                200 non-null    float64
 15  Sick leave(s)                                                                         200 non-null    float64
 16  Audio conversation                                                                    0 non-null      float64
 17  Video of the meeting:                                                                 0 non-null      float64
 18  Communication                                                                         0 non-null      float64
 19  OfficeLaptop                                                                          200 non-null    float64
 20  Periodic employee survey feedbacks                                                    0 non-null      float64
 21  External factors                                                                      0 non-null      float64
 22  Personality style                                                                     200 non-null    object
 23  Mood                                                                                  200 non-null    object
 24  Personality_style_Cat                                                                 200 non-null    int64
 25  burnout                                                                               200 non-null    float64
 26  Employee_burnout                                                                      200 non-null    object
dtypes: float64(15), int64(7), object(5)
memory usage: 42.3+ KB

In [56]:
#Loading the two required columns into a dataset
data = df[['burnout', 'Employee_burnout']]
data

       burnout  Employee_burnout
0    34.769746     Total burnout
1    23.109929  Moderate burnout
2    34.104135     Total burnout
3    30.570959  Alarming burnout
4    28.106541  Alarming burnout
..         ...               ...
195  37.010553     Total burnout
196  33.860771     Total burnout
197  30.997669  Alarming burnout
198  36.320329     Total burnout
199  45.454660     Total burnout

[200 rows x 2 columns]

In [67]:
#Since the last column is in words, it has to be converted into a suitable scale
data['scale']=0
data.loc[data['Employee_burnout']=='No burnout','scale']= 0
data.loc[data['Employee_burnout']=='Alarming burnout','scale']= 1
data.loc[data['Employee_burnout']=='Moderate burnout','scale']= 2
data.loc[data['Employee_burnout']=='Total burnout','scale']= 4
data

       burnout  Employee_burnout  scale
0    34.769746     Total burnout      4
1    23.109929  Moderate burnout      2
2    34.104135     Total burnout      4
3    30.570959  Alarming burnout      1
4    28.106541  Alarming burnout      1
..         ...               ...    ...
195  37.010553     Total burnout      4
196  33.860771     Total burnout      4
197  30.997669  Alarming burnout      1
198  36.320329     Total burnout      4
199  45.454660     Total burnout      4

[200 rows x 3 columns]

In [68]:
#loading the columns in x and y variables
x = data['burnout']
#Reshaping the x columns as a 2D array is expected here
x = x.values.reshape(-1,1)
y = data['scale']

In [69]:
#splitting the test, train dataset
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [70]:
#checking the xtrain dataset
X_train

array([[31.17333601],
       [39.66921907],
       [34.65238254],
       [32.284177  ],
       [39.02365655],
       [34.15402705],
       [23.16579013],
       [28.91377371],
       [29.03295083],
       [29.56795517],
       [32.68116053],
       [30.29027992],
       [36.18348462],
       [34.85612622],
       [28.49530649],
       [36.54874367],
       [37.81310211],
       [30.5969448 ],
       [34.10413456],
       [34.52816466],
       [25.68496923],
       [26.14383438],
       [30.13340972],
       [27.00407507],
       [28.68848833],
       [30.54262686],
       [19.02923774],
       [34.5655887 ],
       [28.04301384],
       [35.194451  ],
       [30.64542306],
       [35.63482802],
       [36.18982125],
       [33.78316167],
       [31.35144205],
       [31.69719357],
       [40.34826179],
       [35.52481805],
       [33.13147007],
       [31.7767733 ],
       [36.8643127 ],
       [31.06449429],
       [26.54703505],
       [37.40324289],
       [31.7455434 ],
       [34.32739371],
       [28.57864474],
       [30.40924086],
       [44.22813261],
       [35.24191605],
       [26.03074512],
       [31.18571573],
       [33.12990271],
       [33.86077135],
       [33.74546028],
       [35.01071672],
       [32.12975707],
       [27.6157869 ],
       [32.55747887],
       [38.18909287],
       [45.45466   ],
       [30.25864521],
       [36.48226764],
       [36.32032907],
       [38.71041345],
       [31.60809372],
       [33.94773936],
       [37.97848297],
       [25.69253895],
       [25.3760986 ],
       [22.24564267],
       [34.54718485],
       [36.91993635],
       [28.2414826 ],
       [32.01212767],
       [35.34586395],
       [37.93993501],
       [39.75040187],
       [28.97199055],
       [31.73175974],
       [38.18925709],
       [29.82043852],
       [30.3415139 ],
       [33.69564026],
       [26.36985891],
       [24.37177312],
       [36.27358907],
       [37.74791087],
       [27.6853114 ],
       [31.98686766],
       [28.97808915],
       [32.99883062],
       [30.17322415],
       [34.48157434],
       [32.29689881],
       [30.99766888],
       [40.13351656],
       [33.91382296],
       [33.13745057],
       [28.88718305],
       [28.08753039],
       [39.9085444 ],
       [26.06813524],
       [32.56437573],
       [38.09363802],
       [32.40817032],
       [35.94399679],
       [29.9487952 ],
       [35.19780164],
       [32.70389532],
       [38.84361681],
       [28.84975737],
       [38.79523521],
       [32.32531981],
       [34.59497531],
       [32.67229667],
       [31.4800529 ],
       [34.52071938],
       [27.90984967],
       [23.26498247],
       [32.2326796 ],
       [32.73928375],
       [31.59356889],
       [36.28326775],
       [18.31865086],
       [30.82959244],
       [30.65273238],
       [30.90547093],
       [24.29183859],
       [25.51166893],
       [29.30513804],
       [36.94462439],
       [38.3472106 ],
       [45.93152277],
       [27.64214203],
       [27.54920364],
       [36.3378919 ],
       [41.87561233],
       [37.05596802],
       [29.88223123],
       [28.22756363],
       [32.43763223],
       [32.00802845],
       [34.32388195],
       [21.40870149],
       [31.7187866 ],
       [37.8253711 ],
       [28.47724881],
       [32.37610092],
       [33.75353973],
       [30.57095905],
       [35.5452365 ],
       [26.73172806],
       [38.25337888],
       [30.3828389 ],
       [22.65271247],
       [28.50646252],
       [25.34190086],
       [28.10654115],
       [24.96834622]])

In [71]:
y_train

124    1
189    4
193    4
96     4
76     4
      ..
72     2
143    1
105    2
4      1
93     2
Name: scale, Length: 160, dtype: int64

In [72]:
models = {
    "                     Linear Regression": LinearRegression(),
    " Linear Regression (L2 Regularization)": Ridge(),
    " Linear Regression (L1 Regularization)": Lasso(),
    "                   K-Nearest Neighbors": KNeighborsRegressor(),
    "                        Neural Network": MLPRegressor(),
    "Support Vector Machine (Linear Kernel)": LinearSVR(),
    "   Support Vector Machine (RBF Kernel)": SVR(),
    "                         Decision Tree": DecisionTreeRegressor(),
    "                         Random Forest": RandomForestRegressor(),
    "                     Gradient Boosting": GradientBoostingRegressor()
}

for name, model in models.items():
    model.fit(X_train, y_train)
    print(name + " trained.")

                     Linear Regression trained.
 Linear Regression (L2 Regularization) trained.
 Linear Regression (L1 Regularization) trained.
                   K-Nearest Neighbors trained.
                        Neural Network trained.
Support Vector Machine (Linear Kernel) trained.
   Support Vector Machine (RBF Kernel) trained.
                         Decision Tree trained.
                         Random Forest trained.
                     Gradient Boosting trained.

In [73]:
for name, model in models.items():
    print(name + " R^2 Score: {:.5f}".format(model.score(X_test, y_test)))

                     Linear Regression R^2 Score: 0.53982
 Linear Regression (L2 Regularization) R^2 Score: 0.53977
 Linear Regression (L1 Regularization) R^2 Score: 0.48316
                   K-Nearest Neighbors R^2 Score: 1.00000
                        Neural Network R^2 Score: 0.33929
Support Vector Machine (Linear Kernel) R^2 Score: 0.53544
   Support Vector Machine (RBF Kernel) R^2 Score: 0.89366
                         Decision Tree R^2 Score: 1.00000
                         Random Forest R^2 Score: 1.00000
                     Gradient Boosting R^2 Score: 1.00000

Therefroe, the best and most accurate models are KNN, Decision tree, Random Forest, Gradient Boosting