In [79]:
#Importing the libraries
import pandas as pd
import random
import numpy as np

In [80]:
#Loading the dataset in a variable
df = pd.read_excel('Burnout Rate.xlsx')
#Reading the first 5 columns of the dataset
df.head()

,Unnamed: 0,Workload,Unnamed: 2,Unnamed: 3,SAP Talk/Feedback Data,Unnamed: 5,Unnamed: 6,MS Teams – User activity report,Unnamed: 8,Unnamed: 9,...,MS Teams – Device usage report,Leave Data,Unnamed: 13,Multi-modalities of data,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20
0,Employee ID,Project ID,Time/Duration,Peer(s) workload,Performance,Missed deadlines,Partly – Job satisfaction,Number of unplanned meetings,Number of meetings organized,Number of meetings participated,...,Time series view of the usage of teams for the...,General leave patterns,Sick leave(s),Audio conversation,Video of the meeting:,Communication,On an office laptop,Periodic employee survey feedbacks,External factors,Personality style
1,fffe320039000123490320,1,8,2,3.8,NaN,Disagree,NaN,NaN,NaN,...,NaN,2,1,NaN,NaN,NaN,NaN,NaN,NaN,INFJ
2,fffe32003000360033003200,2,6,1,5,NaN,Strong Agree,NaN,NaN,NaN,...,NaN,8,4,NaN,NaN,NaN,NaN,NaN,NaN,ENTP
3,fffe3700360033003500,3,6,2,5.8,NaN,Disagree,NaN,NaN,NaN,...,NaN,2,1,NaN,NaN,NaN,NaN,NaN,NaN,INTP
4,fffe31003300320037003900,4,7,1,2.6,NaN,Disagree,NaN,NaN,NaN,...,NaN,2,1,NaN,NaN,NaN,NaN,NaN,NaN,INTJ

In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201 entries, 0 to 200
Data columns (total 21 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Unnamed: 0                       201 non-null    object
 1   Workload                         201 non-null    object
 2   Unnamed: 2                       198 non-null    object
 3   Unnamed: 3                       200 non-null    object
 4   SAP Talk/Feedback Data           176 non-null    object
 5   Unnamed: 5                       1 non-null      object
 6   Unnamed: 6                       201 non-null    object
 7   MS Teams – User activity report  1 non-null      object
 8   Unnamed: 8                       1 non-null      object
 9   Unnamed: 9                       1 non-null      object
 10  Unnamed: 10                      1 non-null      object
 11  MS Teams – Device usage report   1 non-null      object
 12  Leave Data                       200 non-null    object
 13  Unnamed: 13                      200 non-null    object
 14  Multi-modalities of data         1 non-null      object
 15  Unnamed: 15                      1 non-null      object
 16  Unnamed: 16                      1 non-null      object
 17  Unnamed: 17                      1 non-null      object
 18  Unnamed: 18                      1 non-null      object
 19  Unnamed: 19                      1 non-null      object
 20  Unnamed: 20                      201 non-null    object
dtypes: object(21)
memory usage: 33.1+ KB

In [82]:
new_header = df.iloc[0] #grab the first row for the header
df = df[1:] #take the data less the header row
df.columns = new_header #set the header row as the df header
df.head()

,Employee ID,Project ID,Time/Duration,Peer(s) workload,Performance,Missed deadlines,Partly – Job satisfaction,Number of unplanned meetings,Number of meetings organized,Number of meetings participated,...,Time series view of the usage of teams for the purpose of communication or documents,General leave patterns,Sick leave(s),Audio conversation,Video of the meeting:,Communication,On an office laptop,Periodic employee survey feedbacks,External factors,Personality style
1,fffe320039000123490320,1,8,2,3.8,NaN,Disagree,NaN,NaN,NaN,...,NaN,2,1,NaN,NaN,NaN,NaN,NaN,NaN,INFJ
2,fffe32003000360033003200,2,6,1,5,NaN,Strong Agree,NaN,NaN,NaN,...,NaN,8,4,NaN,NaN,NaN,NaN,NaN,NaN,ENTP
3,fffe3700360033003500,3,6,2,5.8,NaN,Disagree,NaN,NaN,NaN,...,NaN,2,1,NaN,NaN,NaN,NaN,NaN,NaN,INTP
4,fffe31003300320037003900,4,7,1,2.6,NaN,Disagree,NaN,NaN,NaN,...,NaN,2,1,NaN,NaN,NaN,NaN,NaN,NaN,INTJ
5,fffe32003400380032003900,5,7,3,6.9,NaN,Neither,NaN,NaN,NaN,...,NaN,4,2,NaN,NaN,NaN,NaN,NaN,NaN,ENTJ

In [83]:
#Function To Print random numbers in project ID
list1 = [] #EmptyList
def proid():
    l1 = random.randint(1, 15)
    list1.append(l1)

In [84]:
#Function To Print random numbers in Missed deadlines
list2 = [] #EmptyList
def mdead():
    l2 = random.randint(0, 15)
    list2.append(l2)

In [85]:
#Function To Print random numbers in number of unplanned meetings
list3 = [] #EmptyList
def unplan():
    l3 = random.randint(3, 15)
    list3.append(l3)

In [86]:
#Function To Print random numbers in Number of meetings organized
list4 = [] #EmptyList
def meorg():
    l4 = random.randint(0, 8)
    list4.append(l4)

In [87]:
#Function To Print random numbers in Number of meetings participated
list5 = [] #EmptyList
def mepart():
    l5 = random.uniform(0, 15)
    list5.append(l5)

In [88]:
#Function To Print random numbers in avg meeting participated
list6 = [] #EmptyList
def avgme():
    l6 = random.uniform(0, 6)
    list6.append(l6)

In [89]:
#Function To Print random numbers in office laptop
list7 = [] #EmptyList
def olap():
    l7 = random.uniform(8, 16)
    list7.append(l7)

In [90]:
for i in range(0,200):
    proid()
    mdead()
    unplan()
    meorg()
    mepart()
    avgme()
    olap()

#Calling the functions so that the data is collected in the respective lists

In [91]:
#Assigning each empty column with the list that we have made
df['Project ID'] = list1
df['Missed deadlines'] = list2
df['Number of unplanned meetings'] = list3
df['Number of meetings organized'] = list4
df['Number of meetings participated'] = list5
df['Average meeting time per day/week'] = list6
df['On an office laptop'] = list7

In [92]:
#Checking the dataframe
df.head()

,Employee ID,Project ID,Time/Duration,Peer(s) workload,Performance,Missed deadlines,Partly – Job satisfaction,Number of unplanned meetings,Number of meetings organized,Number of meetings participated,...,Time series view of the usage of teams for the purpose of communication or documents,General leave patterns,Sick leave(s),Audio conversation,Video of the meeting:,Communication,On an office laptop,Periodic employee survey feedbacks,External factors,Personality style
1,fffe320039000123490320,4,8,2,3.8,13,Disagree,8,5,11.680764,...,NaN,2,1,NaN,NaN,NaN,15.969746,NaN,NaN,INFJ
2,fffe32003000360033003200,13,6,1,5,13,Strong Agree,10,3,13.900930,...,NaN,8,4,NaN,NaN,NaN,8.109929,NaN,NaN,ENTP
3,fffe3700360033003500,13,6,2,5.8,11,Disagree,9,0,4.524665,...,NaN,2,1,NaN,NaN,NaN,12.304135,NaN,NaN,INTP
4,fffe31003300320037003900,14,7,1,2.6,11,Disagree,12,8,10.236268,...,NaN,2,1,NaN,NaN,NaN,12.970959,NaN,NaN,INTJ
5,fffe32003400380032003900,2,7,3,6.9,12,Neither,13,4,14.914313,...,NaN,4,2,NaN,NaN,NaN,9.206541,NaN,NaN,ENTJ

In [93]:
#checking which dataset has empty values
df.isna().sum()

0
Employee ID                                                                               0
Project ID                                                                                0
Time/Duration                                                                             3
Peer(s) workload                                                                          1
Performance                                                                              25
Missed deadlines                                                                          0
Partly – Job satisfaction                                                                 0
Number of unplanned meetings                                                              0
Number of meetings organized                                                              0
Number of meetings participated                                                           0
Average meeting time per day/week                                                         0
Time series view of the usage of teams for the purpose of communication or documents    200
General leave patterns                                                                    1
Sick leave(s)                                                                             1
Audio conversation                                                                      200
Video of the meeting:                                                                   200
Communication                                                                           200
On an office laptop                                                                       0
Periodic employee survey feedbacks                                                      200
External factors                                                                        200
Personality style                                                                         0
dtype: int64

In [94]:
#converting the columns into the right the data type
df['Time/Duration'] = df['Time/Duration'].astype(float)
df['General leave patterns'] = df['General leave patterns'].astype(float)
df['Sick leave(s)'] = df['Sick leave(s)'].astype(float)
df['On an office laptop'] = df['On an office laptop'].astype(float)

In [95]:
#Filling the empty values with mean value
df['Performance'] = df['Performance'].fillna(df['Performance'].mean())
df['Time/Duration'] = df['Time/Duration'].fillna(df['Time/Duration'].mean())
df['General leave patterns'] = df['General leave patterns'].fillna(df['General leave patterns'].mean())
df['Sick leave(s)'] = df['Sick leave(s)'].fillna(df['Sick leave(s)'].mean())

In [96]:
#checking final value
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 1 to 200
Data columns (total 21 columns):
 #   Column                                                                                Non-Null Count  Dtype
---  ------                                                                                --------------  -----
 0   Employee ID                                                                           200 non-null    object
 1   Project ID                                                                            200 non-null    int64
 2   Time/Duration                                                                         200 non-null    float64
 3   Peer(s) workload                                                                      199 non-null    object
 4   Performance                                                                           200 non-null    float64
 5   Missed deadlines                                                                      200 non-null    int64
 6   Partly – Job satisfaction                                                             200 non-null    object
 7   Number of unplanned meetings                                                          200 non-null    int64
 8   Number of meetings organized                                                          200 non-null    int64
 9   Number of meetings participated                                                       200 non-null    float64
 10  Average meeting time per day/week                                                     200 non-null    float64
 11  Time series view of the usage of teams for the purpose of communication or documents  0 non-null      object
 12  General leave patterns                                                                200 non-null    float64
 13  Sick leave(s)                                                                         200 non-null    float64
 14  Audio conversation                                                                    0 non-null      object
 15  Video of the meeting:                                                                 0 non-null      object
 16  Communication                                                                         0 non-null      object
 17  On an office laptop                                                                   200 non-null    float64
 18  Periodic employee survey feedbacks                                                    0 non-null      object
 19  External factors                                                                      0 non-null      object
 20  Personality style                                                                     200 non-null    object
dtypes: float64(7), int64(4), object(10)
memory usage: 32.9+ KB

In [97]:
df.to_excel('Burnout rate - After Cleanse.xlsx')