In [1]:
import pandas as pd 
#loading the dataset
df = pd.read_excel('Burnout Rate - Before modelling.xlsx')
df.head()

,Unnamed: 0,Unnamed: 0.1,Employee ID,Project ID,Duration,Workload,Performance,Missed deadlines,Partly – Job satisfaction,Number of unplanned meetings,...,Video of the meeting:,Communication,OfficeLaptop,Periodic employee survey feedbacks,External factors,Personality style,Mood,Personality_style_Cat,burnout,Employee_burnout
0,0,1,fffe320039000123490320,4,8.0,2.0,3.8,13,Disagree,8,...,NaN,NaN,15.969746,NaN,NaN,INFJ,Positive,5,34.769746,Total burnout
1,1,2,fffe32003000360033003200,13,6.0,1.0,5.0,13,Strong Agree,10,...,NaN,NaN,8.109929,NaN,NaN,ENTP,Positive,3,23.109929,Moderate burnout
2,2,3,fffe3700360033003500,13,6.0,2.0,5.8,11,Disagree,9,...,NaN,NaN,12.304135,NaN,NaN,INTP,Positive,8,34.104135,Total burnout
3,3,4,fffe31003300320037003900,14,7.0,1.0,2.6,11,Disagree,12,...,NaN,NaN,12.970959,NaN,NaN,INTJ,Positive,7,30.570959,Alarming burnout
4,4,5,fffe32003400380032003900,2,7.0,3.0,6.9,12,Neither,13,...,NaN,NaN,9.206541,NaN,NaN,ENTJ,Positive,2,28.106541,Alarming burnout

In [2]:
data = df[['burnout', 'Employee_burnout']]
data

       burnout  Employee_burnout
0    34.769746     Total burnout
1    23.109929  Moderate burnout
2    34.104135     Total burnout
3    30.570959  Alarming burnout
4    28.106541  Alarming burnout
..         ...               ...
195  37.010553     Total burnout
196  33.860771     Total burnout
197  30.997669  Alarming burnout
198  36.320329     Total burnout
199  45.454660     Total burnout

[200 rows x 2 columns]

In [3]:
#Since the last column is in words, it has to be converted into a suitable scale
data['scale']=0
data.loc[data['Employee_burnout']=='No burnout','scale']= 0
data.loc[data['Employee_burnout']=='Alarming burnout','scale']= 1
data.loc[data['Employee_burnout']=='Moderate burnout','scale']= 2
data.loc[data['Employee_burnout']=='Total burnout','scale']= 4
data

<ipython-input-3-3432f6e24aec>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['scale']=0
D:\Sanketh\Softwares\Anaconda\lib\site-packages\pandas\core\indexing.py:1765: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)

       burnout  Employee_burnout  scale
0    34.769746     Total burnout      4
1    23.109929  Moderate burnout      2
2    34.104135     Total burnout      4
3    30.570959  Alarming burnout      1
4    28.106541  Alarming burnout      1
..         ...               ...    ...
195  37.010553     Total burnout      4
196  33.860771     Total burnout      4
197  30.997669  Alarming burnout      1
198  36.320329     Total burnout      4
199  45.454660     Total burnout      4

[200 rows x 3 columns]

In [4]:
#loading the columns in x and y variables
x = data['burnout']
#Reshaping the x columns as a 2D array is expected here
x = x.values.reshape(-1,1)
y = data['scale']

In [6]:
from sklearn import tree

In [7]:
model = tree.DecisionTreeClassifier()

In [8]:
model.fit(x,y)

DecisionTreeClassifier()

In [10]:
model.score(x,y)

1.0

In [14]:
model.predict([[40.221]])

array([4], dtype=int64)